### ISSUE TITLE
Bumping hex

### ISSUE THREAD

**Issue by ddresselhaus** [discord/instruments#13]
I'd like to use Statix 1.2 which is cool with master but not with tag 1.1. If y'all don't mind bumping hex, I'd appreciate it. Thanks!

**Comment by Fitblip** [comment]
Just for the other people following this trail to figure out why their apps aren't reporting metrics with instruments, Statix 1.2 fixes a bug with newer versions of Erlang/OTP where calls will fail so your app will no longer emit metrics.

See https://github.com/discordapp/instruments/pull/11 

+1 to please bumping hex!

**Comment by sb8244** [comment]
I came here to ask for a bump to hex, and found a coworker 🤣 

Currently, I set `override: true` on the statix dep in my app and all is well.

**Comment by mezz** [comment]
Thanks for the heads up 👍. We just published version 1.1.2 to hex here: https://hex.pm/packages/instruments/1.1.2
